
name: update-csvs

on:
  push:
    branches: [ NewControlsIDs ]
  pull_request:
    branches: [ NewControlsIDs ]
    types: [ closed ]

jobs:
  once:
    name: Create local releases
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v2
      with: 
        go-version: 1.18

    - name: Run a update-csv-files script
      run: python ./scripts/update-csv-files.py
    
    - name: Run export script
      run: |
        OUTPUT=pre-release python ./scripts/export.py
        cp -R pre-release releasesDev

    - name: stage changed files
      run: git add .

    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        branch: NewControlsIDs
        github_token: ${{ secrets.GITHUB_TOKEN }} 

